image: registry.gitlab.com/rgozim/docker-registry/gradle-ice36:5.4.1-jdk8

cache:
  paths:
    - .gradle/caches/
    - build/

stages:
  - build
  - publish

build:
  stage: build
  script:
    - gradle build -i
  artifacts:
    paths:
      - "**/build/**/*.jar"
  only:
    refs:
      - develop

publish:
  stage: publish
  script:
    - gradle publishToGitlab -i
  only:
    refs:
      - develop