image: gradle:5.2.1-jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - apt-get update -qq && apt-get install -y -qq zeroc-ice-all-dev
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - publishGitlab

publishToMavenLocal:
  stage: publishGitlab
  script: gradle publish