image: registry.gitlab.com/rgozim/docker-registry/gradle-ice36:5.5.0-jdk8

cache:
  paths:
    - build-cache/
    - "**/.gradle"
    - "**/build"

stages:
  - build
  - snapshot
  - rc

build:
  stage: build
  script:
    - gradle -i -g build-cache build
  artifacts:
    paths:
      - "**/build/**/*.jar"

snapshot:
  stage: snapshot
  script:
    - gradle -i -g build-cache publishToGitlab
  only:
    refs:
      - develop

rc:
  stage: rc
  script:
    - gradle -i -g build-cache publishToGitlab -Preckon.stage=rc
  only:
    refs:
      - staging