image: registry.gitlab.com/rgozim/docker-registry/gradle-ice36:5.4.1-jdk8

cache:
  paths:
    - build-cache/
    - ./**/.gradle/
    - ./**/build/

stages:
  - build
  - publish

build:
  stage: build
  script:
    - gradle -i -g build-cache build
  artifacts:
    paths:
      - "**/build/**/*.jar"
  only:
    refs:
      - develop

publish:
  stage: publish
  script:
    - gradle -i -g build-cache publishToGitlab
  only:
    refs:
      - develop