image: gradle:5.4.1-jdk8

before_script:
  - apt-get update -qq && apt-get install -y -qq zeroc-ice-all-dev
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - publish

build:
  stage: build
  script:
    - gradle --build-cache assemble -i
  cache:
    paths:
      - "**/build/"
  artifacts:
    paths:
      - "**/build/**/*.jar"

publish:
  stage: publish
  script:
    - env
    - gradle publishToGitlab -i
  only:
    - develop