image: gradle:5.4.1-jdk8

before_script:
  - apt-get update -qq && apt-get install -y -qq zeroc-ice-all-dev

stages:
  - build
  - publish

build:
  stage: build
  script:
    - gradle assemble -i
  artifacts:
    paths:
      - "**/build/**/*.jar"

publish:
  stage: publish
  script:
    - env
    - gradle publishToGitlab -i
  only:
    - develop