image: gradle:5.4.0-jdk8

before_script:
  - apt-get update -qq && apt-get install -y -qq zeroc-ice-all-dev
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - publish

build:
  stage: build
  script:
    - gradle assemble -i
  artifacts:
    paths:
      - ice-builder-gradle/build/libs/slice-1.5.0-SNAPSHOT.jar
      - omero-api-plugin/build/libs/omero-api-plugin-5.5.0-SNAPSHOT.jar
      - omero-artifact-plugin/build/libs/omero-artifact-plugin-5.5.0-SNAPSHOT.jar
      - omero-blitz-plugin/build/libs/omero-blitz-plugin-5.5.0-SNAPSHOT.jar
      - omero-dsl-plugin/build/libs/omero-dsl-plugin-5.5.0-SNAPSHOT.jar
      - omero-javapackager-plugin/build/libs/omero-javapackager-plugin-5.5.0-SNAPSHOT.jar

publish:
  stage: publish
  script:
    - env
    - gradle publishToGitlab -i
  only:
    - develop